/*
 * This header is generated by weak_classdump 0.0.1
 * on Tuesday, November 15, 2011 2:36:05 PM Eastern European Time
 * Operating System: Version 5.0 (Build 9A334)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

@interface BBBulletin : NSObject <NSCopying> <NSCoding> {
	NSString* _sectionID; 
	NSString* _publisherRecordID; 
	NSString* _publisherBulletinID; 
	int _addressBookRecordID; 
	int _sectionSubtype; 
	BBContent* _content; 
	BBContent* _modalAlertContent; 
	NSDate* _date; 
	NSDate* _endDate; 
	NSDate* _recencyDate; 
	int _dateFormatStyle; 
	BOOL _dateIsAllDay; 
	NSTimeZone* _timeZone; 
	int _accessoryStyle; 
	BOOL _clearable; 
	BBSound* _sound; 
	BBAttachments* _attachments; 
	NSString* _unlockActionLabelOverride; 
	NSMutableDictionary* _actions; 
	NSArray* _buttons; 
	BOOL _expiresOnPublisherDeath; 
	NSDictionary* _context; 
	NSDate* _expirationDate; 
	NSString* _bulletinID; 
	NSDate* _lastInterruptDate; 
	BBAssertion* _lifeAssertion; 
	BBObserver* _observer; 
	unsigned realertCount_deprecated; 
	NSSet* alertSuppressionAppIDs_deprecated; 
}
@property (nonatomic,copy) BOOL showsSubtitle; 
@property (nonatomic,copy) unsigned messageNumberOfLines; 
@property (nonatomic,copy) BOOL usesVariableLayout; 
@property (nonatomic,copy) BOOL orderSectionUsingRecencyDate; 
@property (nonatomic,copy) BOOL showsDateInFloatingLockScreenAlert; 
@property (nonatomic,copy) NSString* topic; 
@property (nonatomic,copy) NSString* missedBannerDescriptionFormat; 
@property (nonatomic,copy) NSString* fullUnlockActionLabel; 
@property (nonatomic,copy) NSString* unlockActionLabel; 
@property (nonatomic,copy) NSSet* alertSuppressionAppIDs; 
@property (nonatomic,copy) BOOL coalescesWhenLocked; 
@property (nonatomic,copy) BOOL suppressesMessageForPrivacy; 
@property (nonatomic,copy) unsigned realertCount; 
@property (nonatomic,copy) BOOL inertWhenLocked; 
@property (nonatomic,copy) BOOL preservesUnlockActionCase; 
@property (nonatomic,copy) BOOL bannerShowsSubtitle; 
@property (nonatomic,copy) BOOL visuallyIndicatesWhenDateIsInFuture; 
@property (nonatomic,copy) unsigned subtypePriority; 
@property (nonatomic,copy) int iPodOutAlertType; 
@property (nonatomic,copy) NSString* bulletinID; 	//@synthesize _bulletinID=__bulletinID - In the implementation block
@property (nonatomic,copy) NSString* section; 
@property (nonatomic,copy) NSString* sectionID; 	//@synthesize _sectionID=__sectionID - In the implementation block
@property (nonatomic,copy) NSString* recordID; 	//@synthesize _publisherRecordID=__publisherRecordID - In the implementation block
@property (nonatomic,copy) NSString* publisherBulletinID; 	//@synthesize _publisherBulletinID=__publisherBulletinID - In the implementation block
@property (assign,nonatomic) int addressBookRecordID; 	//@synthesize _addressBookRecordID=__addressBookRecordID - In the implementation block
@property (assign,nonatomic) int sectionSubtype; 	//@synthesize _sectionSubtype=__sectionSubtype - In the implementation block
@property (nonatomic,copy) NSString* title; 
@property (nonatomic,copy) NSString* subtitle; 
@property (nonatomic,copy) NSString* message; 
@property (nonatomic,retain) BBContent* modalAlertContent; 	//@synthesize _modalAlertContent=__modalAlertContent - In the implementation block
@property (nonatomic,retain) NSDate* date; 	//@synthesize _date=__date - In the implementation block
@property (nonatomic,retain) NSDate* endDate; 	//@synthesize _endDate=__endDate - In the implementation block
@property (nonatomic,retain) NSDate* recencyDate; 	//@synthesize _recencyDate=__recencyDate - In the implementation block
@property (assign,nonatomic) int dateFormatStyle; 	//@synthesize _dateFormatStyle=__dateFormatStyle - In the implementation block
@property (assign,nonatomic) BOOL dateIsAllDay; 	//@synthesize _dateIsAllDay=__dateIsAllDay - In the implementation block
@property (nonatomic,retain) NSTimeZone* timeZone; 	//@synthesize _timeZone=__timeZone - In the implementation block
@property (assign,nonatomic) int accessoryStyle; 	//@synthesize _accessoryStyle=__accessoryStyle - In the implementation block
@property (assign,nonatomic) BOOL clearable; 	//@synthesize _clearable=__clearable - In the implementation block
@property (nonatomic,retain) BBSound* sound; 	//@synthesize _sound=__sound - In the implementation block
@property (nonatomic,copy) int primaryAttachmentType; 
@property (nonatomic,copy) BBAction* defaultAction; 
@property (nonatomic,copy) BBAction* acknowledgeAction; 
@property (nonatomic,copy) BBAction* replyAction; 
@property (nonatomic,copy) NSArray* buttons; 	//@synthesize _buttons=__buttons - In the implementation block
@property (assign,nonatomic) BOOL expiresOnPublisherDeath; 	//@synthesize _expiresOnPublisherDeath=__expiresOnPublisherDeath - In the implementation block
@property (nonatomic,retain) NSDictionary* context; 	//@synthesize _context=__context - In the implementation block
@property (nonatomic,retain) NSDate* lastInterruptDate; 	//@synthesize _lastInterruptDate=__lastInterruptDate - In the implementation block
@property (nonatomic,retain) BBContent* content; 	//@synthesize _content=__content - In the implementation block
@property (nonatomic,retain) BBAttachments* attachments; 	//@synthesize _attachments=__attachments - In the implementation block
@property (nonatomic,copy) NSString* unlockActionLabelOverride; 	//@synthesize _unlockActionLabelOverride=__unlockActionLabelOverride - In the implementation block
@property (nonatomic,retain) NSMutableDictionary* actions; 	//@synthesize _actions=__actions - In the implementation block
@property (nonatomic,retain) NSDate* expirationDate; 	//@synthesize _expirationDate=__expirationDate - In the implementation block
@property (nonatomic,copy) BBAction* expireAction; 
@property (nonatomic,retain) BBAssertion* lifeAssertion; 	//@synthesize _lifeAssertion=__lifeAssertion - In the implementation block
@property (nonatomic,retain) BBObserver* observer; 	//@synthesize _observer=__observer - In the implementation block
@property (assign,nonatomic) unsigned realertCount_deprecated; 
@property (nonatomic,copy) NSSet* alertSuppressionAppIDs_deprecated; 
+(void)killSounds;
+(id)bulletinWithBulletin:(id)arg1;
-(id)launchBlockForButtonIndex:(unsigned)arg1 withOrigin:(int)arg2;
-(id)defaultLaunchBlockWithOrigin:(int)arg1;
-(id)launchBlockForButtonIndex:(unsigned)arg1;
-(id)defaultLaunchBlock;
-(void)killSound;
-(BOOL)playSound;
-(void)setSection:(id)arg1;
-(id)attachments;
-(void)setRecordID:(id)arg1;
-(id)defaultAction;
-(void)setObserver:(id)arg1;
-(id)observer;
-(void)setBulletinID:(id)arg1;
-(id)bulletinID;
-(id)lifeAssertion;
-(void)setLifeAssertion:(id)arg1;
-(void)_fillOutCopy:(id)arg1 withZone:(struct _NSZone*)arg2;
-(id)sectionID;
-(void)setSectionID:(id)arg1;
-(unsigned)numberOfAdditionalAttachments;
-(unsigned)numberOfAdditionalAttachmentsOfType:(int)arg1;
-(id)attachmentsCreatingIfNecessary:(BOOL)arg1;
-(id)_actionKeyForButtonIndex:(unsigned)arg1;
-(id)responseSendBlock;
-(id)_responseForActionKey:(id)arg1;
-(id)expireAction;
-(void)deliverResponse:(id)arg1;
-(id)publisherBulletinID;
-(void)setPublisherBulletinID:(id)arg1;
-(int)addressBookRecordID;
-(void)setAddressBookRecordID:(int)arg1;
-(int)sectionSubtype;
-(void)setSectionSubtype:(int)arg1;
-(id)modalAlertContent;
-(void)setModalAlertContent:(id)arg1;
-(id)recencyDate;
-(void)setRecencyDate:(id)arg1;
-(int)dateFormatStyle;
-(void)setDateFormatStyle:(int)arg1;
-(BOOL)dateIsAllDay;
-(void)setDateIsAllDay:(BOOL)arg1;
-(int)accessoryStyle;
-(void)setAccessoryStyle:(int)arg1;
-(BOOL)clearable;
-(void)setClearable:(BOOL)arg1;
-(id)sound;
-(void)setSound:(id)arg1;
-(id)unlockActionLabelOverride;
-(void)setUnlockActionLabelOverride:(id)arg1;
-(id)lastInterruptDate;
-(void)setLastInterruptDate:(id)arg1;
-(unsigned)realertCount_deprecated;
-(void)setRealertCount_deprecated:(unsigned)arg1;
-(id)alertSuppressionAppIDs_deprecated;
-(void)setAlertSuppressionAppIDs_deprecated:(id)arg1;
-(int)primaryAttachmentType;
-(void)setDefaultAction:(id)arg1;
-(id)acknowledgeAction;
-(void)setAcknowledgeAction:(id)arg1;
-(id)replyAction;
-(void)setReplyAction:(id)arg1;
-(void)setExpireAction:(id)arg1;
-(id)responseForDefaultAction;
-(id)responseForReplyAction;
-(id)responseForAcknowledgeAction;
-(id)responseForButtonActionAtIndex:(unsigned)arg1;
-(id)responseForExpireAction;
-(BOOL)expiresOnPublisherDeath;
-(void)setExpiresOnPublisherDeath:(BOOL)arg1;
-(unsigned)realertCount;
-(BOOL)showsSubtitle;
-(unsigned)messageNumberOfLines;
-(BOOL)usesVariableLayout;
-(BOOL)orderSectionUsingRecencyDate;
-(BOOL)showsDateInFloatingLockScreenAlert;
-(id)missedBannerDescriptionFormat;
-(id)fullUnlockActionLabel;
-(id)unlockActionLabel;
-(id)alertSuppressionAppIDs;
-(BOOL)coalescesWhenLocked;
-(BOOL)suppressesMessageForPrivacy;
-(BOOL)inertWhenLocked;
-(BOOL)preservesUnlockActionCase;
-(BOOL)bannerShowsSubtitle;
-(BOOL)visuallyIndicatesWhenDateIsInFuture;
-(unsigned)subtypePriority;
-(int)iPodOutAlertType;
-(id)composedAttachmentImageForKey:(id)arg1;
-(struct CGSize)composedAttachmentImageSizeForKey:(id)arg1;
-(id)composedAttachmentImage;
-(struct CGSize)composedAttachmentImageSize;
-(id)endDate;
-(void)setEndDate:(id)arg1;
-(id)actions;
-(void)setActions:(id)arg1;
-(void)setAttachments:(id)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)setTitle:(id)arg1;
-(id)date;
-(void)setDate:(id)arg1;
-(void)setTimeZone:(id)arg1;
-(id)title;
-(void)setContext:(id)arg1;
-(id)context;
-(id)section;
-(id)content;
-(void)setSubtitle:(id)arg1;
-(id)subtitle;
-(id)timeZone;
-(id)buttons;
-(void)setMessage:(id)arg1;
-(id)message;
-(void)dealloc;
-(id)init;
-(id)copyWithZone:(struct _NSZone*)arg1;
-(id)description;
-(id)expirationDate;
-(void)setExpirationDate:(id)arg1;
-(id)recordID;
-(void)setButtons:(id)arg1;
-(id)topic;
-(void)setContent:(id)arg1;
@end